"""
AgentGuard - Compliance Report Generator
Generates EU AI Act Annex IV technical documentation, HIPAA audit reports,
and SOX compliance packages in PDF and DOCX formats.
"""
import json
import logging
import os
import uuid
from datetime import datetime
from pathlib import Path
from typing import List, Optional
from dataclasses import dataclass

logger = logging.getLogger("agentguard.reports")
REPORTS_DIR = Path("reports")
REPORTS_DIR.mkdir(exist_ok=True)


@dataclass
class ReportContext:
    agent_id: str
    agent_name: str
    agent_description: str
    provider: str
    model: str
    risk_level: str
    compliance_score: float
    findings: List[dict]
    recommendations: List[str]
    total_interactions: int
    pii_exposures: int
    high_risk_count: int
    period_start: str
    period_end: str
    generated_at: str


class AnnexIVGenerator:
    """
    Generates EU AI Act Annex IV Technical Documentation.
    Required for all high-risk AI systems under the EU AI Act.
    """
    
    ANNEX_IV_SECTIONS = [
        {
            "number": "1",
            "title": "General Description of the AI System",
            "subsections": [
                "1.1 Intended purpose and use cases",
                "1.2 Version and update information", 
                "1.3 Software specifications",
                "1.4 Interaction with other systems"
            ]
        },
        {
            "number": "2",
            "title": "Description of the Elements & Development Process",
            "subsections": [
                "2.1 Training data and methodology",
                "2.2 Design specifications",
                "2.3 System architecture",
                "2.4 Input/output specifications"
            ]
        },
        {
            "number": "3",
            "title": "Performance Monitoring & Logging",
            "subsections": [
                "3.1 Logging mechanisms",
                "3.2 Performance metrics",
                "3.3 Monitoring procedures"
            ]
        },
        {
            "number": "4",
            "title": "Risk Management Documentation",
            "subsections": [
                "4.1 Risk identification",
                "4.2 Risk mitigation measures",
                "4.3 Residual risk assessment"
            ]
        },
        {
            "number": "5",
            "title": "Human Oversight Measures",
            "subsections": [
                "5.1 Oversight mechanisms",
                "5.2 Intervention capabilities",
                "5.3 Override procedures"
            ]
        },
        {
            "number": "6",
            "title": "Post-Market Monitoring Plan",
            "subsections": [
                "6.1 Continuous monitoring procedures",
                "6.2 Incident reporting",
                "6.3 Performance benchmarks"
            ]
        }
    ]
    
    def generate_markdown(self, ctx: ReportContext) -> str:
        """Generate Annex IV documentation in Markdown format."""
        
        now = datetime.fromisoformat(ctx.generated_at).strftime("%d %B %Y")
        
        doc = f"""# EU AI Act — Annex IV Technical Documentation

**System Name:** {ctx.agent_name}  
**Document Version:** 1.0  
**Classification:** {ctx.risk_level.upper()} RISK  
**Generated:** {now}  
**Generated by:** AgentGuard Compliance Platform  

---

> ⚠️ This document has been auto-generated based on AgentGuard audit data.
> It should be reviewed by qualified legal counsel before regulatory submission.

---

## SECTION 1: General Description of the AI System

### 1.1 Intended Purpose and Use Cases

The AI system **{ctx.agent_name}** is deployed for the following intended purposes:

{ctx.agent_description}

**Provider:** {ctx.provider.upper()}  
**Model:** {ctx.model}  
**Risk Classification (EU AI Act):** {ctx.risk_level.capitalize()} Risk  

### 1.2 Version and Update Information

| Parameter | Value |
|-----------|-------|
| Document Date | {now} |
| Model Version | {ctx.model} |
| Monitoring Period | {ctx.period_start[:10]} to {ctx.period_end[:10]} |
| Last Updated | {now} |

### 1.3 Software Specifications

- **Deployment Environment:** Cloud-hosted via API
- **Integration Type:** API-based AI agent
- **Intercepted via:** AgentGuard middleware (non-invasive monitoring)
- **Data Processing Location:** As per {ctx.provider.capitalize()} data processing agreement

### 1.4 Interaction with Other Systems

The AI agent interacts with the following systems (as detected by AgentGuard):
- **AI Model API:** {ctx.provider.capitalize()} ({ctx.model})
- **Monitoring Layer:** AgentGuard compliance platform
- **Audit Database:** Encrypted audit log storage

---

## SECTION 2: Development Process & Technical Architecture

### 2.1 Training Data and Methodology

*Note: Training data details are managed by {ctx.provider.capitalize()} as the foundation model provider. 
Refer to {ctx.provider.capitalize()}'s model card and terms of service for training data documentation.*

**Custom Fine-tuning:** None (base model deployment)  
**System Prompts:** Documented and version-controlled (see internal records)

### 2.2 Design Specifications

| Specification | Details |
|--------------|---------|
| Input Types | Text (prompts, user messages) |
| Output Types | Text (model responses) |
| Tool Use | Logged via AgentGuard interceptor |
| Context Window | Per model specifications |
| Languages | As supported by {ctx.model} |

### 2.3 System Architecture

```
User Input → Application Layer → AgentGuard Interceptor
     ↓                                    ↓
[Risk Scoring]              [Audit Log + PII Detection]
     ↓                                    ↓
{ctx.provider.capitalize()} AI API ←→ Compliance Flags
     ↓
Response → User
```

### 2.4 Input/Output Specifications

**Inputs monitored:**
- User prompts and conversation history
- Tool/function call parameters
- System prompt configuration

**Outputs logged (hashed for privacy):**
- Model text responses (SHA-256 hash stored)
- Tool call results
- Token usage metrics

---

## SECTION 3: Performance Monitoring & Logging

### 3.1 Logging Mechanisms

AgentGuard provides comprehensive audit logging with:

- ✅ Immutable, timestamped audit trail
- ✅ SHA-256 hashing of all content (privacy-preserving)
- ✅ PII detection and flagging
- ✅ Risk score calculation per interaction
- ✅ Compliance flag generation in real-time

**Monitoring Period Statistics:**

| Metric | Value |
|--------|-------|
| Total Interactions Logged | {ctx.total_interactions:,} |
| PII Exposures Detected | {ctx.pii_exposures} |
| High-Risk Interactions | {ctx.high_risk_count} |
| Compliance Score | {ctx.compliance_score:.1f}/100 |

### 3.2 Performance Metrics

The system is evaluated on the following compliance KPIs:

| KPI | Target | Actual |
|-----|--------|--------|
| Audit Coverage | 100% | {"100%" if ctx.total_interactions > 0 else "0% - Logging not active"} |
| PII Mitigation Rate | >95% | {"Monitoring active" if ctx.total_interactions > 0 else "N/A"} |
| Response Availability | >99.9% | Per provider SLA |
| Compliance Score | >80 | {ctx.compliance_score:.1f} |

### 3.3 Monitoring Procedures

**Daily:** Automated risk score review via AgentGuard dashboard  
**Weekly:** Compliance flag review and remediation  
**Monthly:** Full compliance report generation (this document type)  
**Annually:** Third-party audit readiness review

---

## SECTION 4: Risk Management Documentation

### 4.1 Risk Identification

Based on EU AI Act Article 9, the following risks have been identified:

**Risk Classification:** {ctx.risk_level.capitalize()} Risk

{"**⚠️ High-Risk Obligations Apply:** This system falls under Annex III of the EU AI Act and must comply with Articles 9-16 requirements." if ctx.risk_level == "high" else "**✅ Minimal/Limited Risk:** Standard obligations apply. Voluntary code of conduct recommended."}

**Identified Risk Factors:**
{chr(10).join(f"- {f['title']}: {f['description']}" for f in ctx.findings[:5])}

### 4.2 Risk Mitigation Measures

Implemented mitigations:
- **AgentGuard Monitoring:** Real-time PII detection and risk scoring
- **Audit Trail:** Immutable log of all AI interactions
- **Compliance Scanning:** Automated gap analysis against EU AI Act requirements
- **Alert System:** Immediate notification of high-risk interactions

### 4.3 Residual Risk Assessment

After implemented controls, residual risks include:
- Foundation model behavior outside training distribution
- User jailbreak attempts (monitored via AgentGuard)
- Third-party API availability dependencies

**Residual Risk Level:** {"HIGH - Requires immediate attention to open findings" if ctx.compliance_score < 60 else "MEDIUM - Monitor and address open findings" if ctx.compliance_score < 80 else "LOW - Maintain current controls"}

---

## SECTION 5: Human Oversight Measures

### 5.1 Oversight Mechanisms

Per EU AI Act Article 14, human oversight measures:

- 📊 AgentGuard dashboard provides real-time oversight capability
- 🚨 Automated alerts for high-risk interactions requiring human review
- 📋 Monthly compliance reports reviewed by responsible person
- 🔍 Audit logs available for inspection at any time

### 5.2 Intervention Capabilities

Operators can intervene in AI system operation via:
- API key rotation to immediately stop agent operation
- System prompt modification to constrain agent behavior
- AgentGuard block-list configuration for prohibited content

### 5.3 Override Procedures

**Emergency stop procedure:**
1. Rotate/revoke API credentials in {ctx.provider.capitalize()} console
2. Notify affected users within 72 hours per GDPR Article 33
3. Document incident in AgentGuard incident log
4. Root cause analysis within 5 business days

---

## SECTION 6: Post-Market Monitoring Plan

### 6.1 Continuous Monitoring Procedures

AgentGuard provides automated post-market monitoring:

| Monitoring Type | Frequency | Responsible |
|----------------|-----------|-------------|
| Risk score review | Real-time | AgentGuard automated |
| Compliance score | Monthly | Compliance officer |
| PII exposure review | Weekly | Privacy team |
| Model performance | Quarterly | Technical lead |
| Full compliance audit | Annually | External auditor |

### 6.2 Incident Reporting

**Reporting thresholds:**
- Risk score > 0.8: Immediate alert + investigation within 24h
- PII exposure: Log + notify privacy officer within 48h
- System outage: Notify users per SLA commitments
- Regulatory incidents: Report per applicable regulations

### 6.3 Performance Benchmarks

| Benchmark | Target | Review Frequency |
|-----------|--------|-----------------|
| Compliance Score | ≥ 80/100 | Monthly |
| Critical Findings | 0 | Weekly |
| High-Risk Interactions | < 2% of total | Monthly |
| PII Exposures Unmitigated | 0 | Daily |

---

## RECOMMENDATIONS

{"".join(f"{i+1}. {rec}{chr(10)}" for i, rec in enumerate(ctx.recommendations))}

---

## OPEN FINDINGS REQUIRING REMEDIATION

{"No critical or high findings. System is substantially compliant." if not ctx.findings else ""}
{"".join(f"""
### Finding {i+1}: {f.get('title', 'N/A')} [{f.get('severity', 'unknown').upper()}]
**Code:** {f.get('code', 'N/A')}  
**Regulation:** {f.get('article', 'N/A')}  
**Description:** {f.get('description', 'N/A')}  
**Remediation:** {f.get('remediation', 'See compliance team')}  
""" for i, f in enumerate(ctx.findings))}

---

## DECLARATION

This technical documentation has been prepared in accordance with EU AI Act Annex IV requirements.
The information contained herein is accurate to the best of the operator's knowledge as of the document date.

**Prepared by:** AgentGuard Automated Compliance System  
**Review Required by:** Qualified compliance officer / legal counsel  
**Document Date:** {now}  
**Next Review:** {(datetime.fromisoformat(ctx.generated_at).replace(month=datetime.fromisoformat(ctx.generated_at).month % 12 + 1)).strftime("%d %B %Y")}  

---
*Generated by AgentGuard v1.0 | EU AI Act Annex IV Template | Not legal advice*
"""
        return doc
    
    def save_to_file(self, ctx: ReportContext) -> str:
        """Save report to file and return path."""
        content = self.generate_markdown(ctx)
        filename = f"annex_iv_{ctx.agent_id[:8]}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        filepath = REPORTS_DIR / filename
        filepath.write_text(content, encoding="utf-8")
        logger.info(f"Annex IV report saved: {filepath}")
        return str(filepath)


class ReportGenerator:
    """Main report generation orchestrator."""
    
    def __init__(self):
        self.annex_iv = AnnexIVGenerator()
    
    async def generate_annex_iv(self, agent_id: str, compliance_data: dict) -> str:
        """Generate EU AI Act Annex IV documentation."""
        ctx = ReportContext(
            agent_id=agent_id,
            agent_name=compliance_data.get("agent_name", "AI Agent"),
            agent_description=compliance_data.get("description", "AI-powered business workflow automation"),
            provider=compliance_data.get("provider", "openai"),
            model=compliance_data.get("model", "gpt-4o-mini"),
            risk_level=compliance_data.get("risk_level", "limited"),
            compliance_score=compliance_data.get("overall_score", 0.0),
            findings=compliance_data.get("findings", []),
            recommendations=compliance_data.get("recommendations", []),
            total_interactions=compliance_data.get("total_interactions", 0),
            pii_exposures=compliance_data.get("pii_exposures", 0),
            high_risk_count=compliance_data.get("high_risk_interactions", 0),
            period_start=compliance_data.get("period_start", datetime.utcnow().isoformat()),
            period_end=compliance_data.get("period_end", datetime.utcnow().isoformat()),
            generated_at=datetime.utcnow().isoformat()
        )
        
        return self.annex_iv.save_to_file(ctx)
    
    async def generate_audit_summary(self, agent_id: str, period_days: int = 30) -> str:
        """Generate an audit summary report."""
        import aiosqlite
        
        try:
            async with aiosqlite.connect("agentguard.db") as db:
                db.row_factory = aiosqlite.Row
                cursor = await db.execute("""
                    SELECT * FROM audit_logs 
                    WHERE agent_id = ?
                    ORDER BY timestamp DESC
                    LIMIT 1000
                """, (agent_id,))
                logs = await cursor.fetchall()
        except:
            logs = []
        
        filename = f"audit_summary_{agent_id[:8]}_{datetime.now().strftime('%Y%m%d')}.md"
        filepath = REPORTS_DIR / filename
        
        content = f"""# Audit Summary Report

**Agent ID:** {agent_id}  
**Generated:** {datetime.utcnow().strftime("%d %B %Y %H:%M UTC")}  
**Total Records:** {len(logs)}  

## Audit Log Summary

| Timestamp | Event | Risk Score | PII | Flags |
|-----------|-------|-----------|-----|-------|
"""
        for log in logs[:50]:
            content += f"| {dict(log).get('timestamp', '')[:19]} | {dict(log).get('event_type', '')} | {dict(log).get('risk_score', 0):.2f} | {'✅' if dict(log).get('pii_detected') else '❌'} | {len(json.loads(dict(log).get('compliance_flags', '[]')))} |\n"
        
        if len(logs) > 50:
            content += f"\n*... and {len(logs) - 50} more records. Full export available via API.*\n"
        
        filepath.write_text(content, encoding="utf-8")
        return str(filepath)
